# Generated by Django 6.0.1 on 2026-05-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('supervisor_name', models.CharField(max_length=100)),
                ('supervisor_photo', models.ImageField(upload_to='staff/')),
                ('supervisor_email', models.EmailField(max_length=254)),
                ('manager_name', models.CharField(max_length=100)),
                ('manager_photo', models.ImageField(upload_to='staff/')),
                ('manager_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Образовательная программа',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='students/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('role', models.CharField(choices=[('me', 'Я'), ('classmate', 'Однокурсник')], default='classmate', max_length=100)),
            ],
            options={
                'verbose_name': 'Студент',
            },
        ),
    ]
