# Generated by Django 6.0.1 on 2026-05-06 11:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Образовательная программа', 'verbose_name_plural': 'Образовательные программы'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(verbose_name='Описание программы'),
        ),
        migrations.AlterField(
            model_name='program',
            name='manager_email',
            field=models.EmailField(max_length=254, verbose_name='Email менеджера'),
        ),
        migrations.AlterField(
            model_name='program',
            name='manager_name',
            field=models.CharField(max_length=100, verbose_name='Менеджер (ФИО)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='manager_photo',
            field=models.ImageField(upload_to='staff/', verbose_name='Фото менеджера'),
        ),
        migrations.AlterField(
            model_name='program',
            name='supervisor_email',
            field=models.EmailField(max_length=254, verbose_name='Email декана'),
        ),
        migrations.AlterField(
            model_name='program',
            name='supervisor_name',
            field=models.CharField(max_length=100, verbose_name='Декан (ФИО)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='supervisor_photo',
            field=models.ImageField(upload_to='staff/', verbose_name='Фото декана'),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название программы'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='students/', verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200, verbose_name='Ник')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Оценка')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='myapp.program', verbose_name='Образовательная программа')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_date'],
            },
        ),
    ]
