# Generated by Django 6.0.1 on 2026-05-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_program_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок страницы')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-адрес')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в навигации')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать в навигации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['order', 'title'],
            },
        ),
    ]
