# Generated by Django 6.0.1 on 2026-05-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_page_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_a', models.FloatField(verbose_name='Ребро куба A')),
                ('input_h', models.FloatField(verbose_name='Высота H')),
                ('input_r', models.FloatField(verbose_name='Радиус R')),
                ('input_m', models.FloatField(verbose_name='Объём M')),
                ('result_text', models.CharField(max_length=200, verbose_name='Результат')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Результат задачи',
                'verbose_name_plural': 'Результаты задачи',
                'ordering': ['-created_at'],
            },
        ),
    ]
